In [1]:
 # Dependencies
from bs4 import BeautifulSoup
import requests
from splinter import Browser
import pandas as pd

In [2]:
csv_file_path = ("../Car price data/altima_data.csv")

In [3]:
# Using Splinter Scraping data
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)
# URL of page to be scraped
url = 'https://losangeles.craigslist.org/search/cto?min_price=2000&auto_make_model=Altima&min_auto_year=2008&max_auto_year=2018&min_auto_miles=0&max_auto_miles=1000000&condition=10&condition=20&condition=30&condition=40'

In [4]:
# Scrape the data based on post info
browser.visit(url)
html = browser.html
soup = BeautifulSoup(html,"html.parser")
next_page = soup.find("a",class_ = "button next")["href"]

titles = []
prices = []
links = []
car_data = []

while next_page:
    print(" - - - - - - - - - - - Scraping New Page Starts!! - - - - - - - - - ")
    html = browser.html
    soup = BeautifulSoup(html,"html.parser")
    results = soup.find_all('li', class_="result-row")
    
    
    
    
    for result in results:
    # Error handling
        try:
            # Identify and return title of listing
            title = result.find('a', class_="result-title").text
            # Identify and return price of listing
            price = result.a.span.text
            # Identify and return link to listing
            link = result.a['href']

            # Print results only if title, price, and link are available
            if (title and price and link):
                titles.append(title)
                prices.append(price)
                links.append(link)
                
                post_link = result.a["href"]
                response2 = requests.get(post_link)
                soup2 = BeautifulSoup(response2.text,"html.parser")
                attributes = soup2.find_all("p",class_="attrgroup")
                attribute_list = attributes[1].find_all("span")
                yearlist = [str(num) for num in list(range(1900, 2020))]
                tag = attributes[0].find_
                attr_dic = {}
                for attr in attribute_list:
                    try:
                        key,value = attr.text.split(":")
                        attr_dic[key] = value
                    except ValueError:
                        pass
    
                car_data.append(attr_dic)
                
                
        except AttributeError as e:
            print(e)
    try:
        browser.click_link_by_partial_text('next')
        next_page = soup.find("a",class_ = "button next")["href"]
    except:
        print("- - - - - - - - - This is the last page we can find!!!- - - - - -")
        next_page = False

 - - - - - - - - - - - Scraping New Page Starts!! - - - - - - - - -
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
 - - - - - - - - - - - Scraping New Page Starts!! - - - - - - - - -
'NoneType' object has no attribute 'text'
- - - - - - - - - This is the last page we can find!!!- - - - - -

In [5]:
# Store info as dataframe
info_df = pd.DataFrame({
    "Info" : titles,
    "Price" : prices,
    "links" : links
})

In [15]:
# Show full dataframe
pd.set_option('display.max_colwidth', -1)
# Merge two dataframe
car_df = pd.DataFrame(car_data)
car_df["Title"] = info_df["Info"]
car_df["Price"] = info_df["Price"]
car_df["links"] = info_df["links"]
car_df["Make"] = "Nissan"
car_df["Model"] = "Altima"
car_df.tail(50)

,VIN,condition,cylinders,drive,fuel,odometer,paint color,size,title status,transmission,type,Title,Price,links,Make,Model
103,NaN,excellent,4 cylinders,fwd,gas,103000,blue,full-size,salvage,automatic,sedan,2010 Nissan Altima,$5000,https://losangeles.craigslist.org/sfv/cto/d/2010-nissan-altima/6698920039.html,Nissan,Altima
104,NaN,excellent,4 cylinders,NaN,gas,91300,black,NaN,clean,automatic,NaN,*Great Deal* 2013 Nissan Altima SV,$8900,https://losangeles.craigslist.org/wst/cto/d/great-deal-2013-nissan-altima/6694700731.html,Nissan,Altima
105,NaN,good,4 cylinders,fwd,gas,134000,white,full-size,clean,automatic,pickup,09 Nissan Altima,$5000,https://losangeles.craigslist.org/sfv/cto/d/09-nissan-altima/6698319269.html,Nissan,Altima
106,NaN,good,4 cylinders,rwd,gas,75054,grey,mid-size,clean,automatic,sedan,2015 Nissan Altima 2.5,$9900,https://losangeles.craigslist.org/lgb/cto/d/2015-nissan-altima-25/6698304977.html,Nissan,Altima
107,NaN,good,4 cylinders,fwd,gas,123000,red,full-size,salvage,automatic,NaN,2014 Nissan Altima,$6000,https://losangeles.craigslist.org/sfv/cto/d/2014-nissan-altima/6698118064.html,Nissan,Altima
108,NaN,new,4 cylinders,fwd,gas,20000,black,mid-size,clean,automatic,sedan,"2016 NISSAN ALTIMA SR, BLACK/BLACK INT 4 CILINDERS",$16400,https://losangeles.craigslist.org/sfv/cto/d/2016-nissan-altima-sr-black/6680802511.html,Nissan,Altima
109,NaN,like new,4 cylinders,fwd,gas,99552,white,mid-size,clean,automatic,sedan,"2015 Nissan Altima S,No Accidents,Well Maintained!!",$9995,https://losangeles.craigslist.org/lac/cto/d/2015-nissan-altima-sno/6696446922.html,Nissan,Altima
110,NaN,good,NaN,NaN,hybrid,200000,NaN,NaN,clean,automatic,NaN,Nissan Altima Hybrid 2008,$3000,https://losangeles.craigslist.org/lac/cto/d/nissan-altima-hybrid-2008/6696433476.html,Nissan,Altima
111,NaN,excellent,4 cylinders,fwd,gas,16000,black,full-size,clean,automatic,sedan,2017 NISSAN ALTIMA SL 16K MILAGE LEATHER,$15900,https://losangeles.craigslist.org/sgv/cto/d/2017-nissan-altima-sl-16k/6671425177.html,Nissan,Altima
112,NaN,excellent,4 cylinders,fwd,gas,67000,white,mid-size,clean,automatic,sedan,"2012 Nissan Altima * 4 Cly * Auto * * Sale, Sale, Sale * *",$7495,https://losangeles.craigslist.org/wst/cto/d/2012-nissan-altima-4-cly-auto/6671805958.html,Nissan,Altima
113,NaN,excellent,4 cylinders,fwd,diesel,185000,NaN,mid-size,clean,other,coupe,2010 Nissan Altima,$5350,https://losangeles.craigslist.org/lac/cto/d/2010-nissan-altima/6696177586.html,Nissan,Altima
114,NaN,excellent,4 cylinders,fwd,gas,118000,black,mid-size,clean,automatic,sedan,2012 *********************** NISSAN ALTIMA,$7600,https://losangeles.craigslist.org/lac/cto/d/2012-nissan-altima/6672058724.html,Nissan,Altima
115,NaN,good,NaN,NaN,gas,120754,grey,NaN,clean,automatic,NaN,2009 Nissan Altima for Sale,$4200,https://losangeles.craigslist.org/wst/cto/d/2009-nissan-altima-for-sale/6689072189.html,Nissan,Altima
116,NaN,good,4 cylinders,rwd,gas,87,black,compact,clean,automatic,sedan,2012 NISSAN ALTIMA,$6700,https://losangeles.craigslist.org/lgb/cto/d/2012-nissan-altima/6696043506.html,Nissan,Altima
117,NaN,good,4 cylinders,rwd,gas,87,black,compact,clean,automatic,sedan,2012 NISSAN ALTIMA,$6700,https://losangeles.craigslist.org/lgb/cto/d/2012-nissan-altima/6696043506.html,Nissan,Altima
118,1N4AL2AP3BN455469,excellent,4 cylinders,NaN,gas,115000,black,NaN,clean,automatic,sedan,2011 NISSAN ALTIMA 2.5 S,$6900,https://losangeles.craigslist.org/lac/cto/d/2011-nissan-altima-25/6695562407.html,Nissan,Altima
119,NaN,like new,4 cylinders,fwd,gas,28000,brown,full-size,salvage,automatic,sedan,2015 Nissan Altima SV,$9500,https://losangeles.craigslist.org/lac/cto/d/2015-nissan-altima-sv/6695548967.html,Nissan,Altima
120,NaN,good,4 cylinders,NaN,gas,115000,NaN,NaN,clean,automatic,NaN,2009 Nissan Altima,$5000,https://losangeles.craigslist.org/sfv/cto/d/2009-nissan-altima/6695057723.html,Nissan,Altima
121,NaN,good,4 cylinders,rwd,gas,87,black,compact,clean,automatic,sedan,2012 NISSAN ALTIMA,$6500,https://losangeles.craigslist.org/lgb/cto/d/2012-nissan-altima/6694973340.html,Nissan,Altima
122,NaN,good,4 cylinders,NaN,gas,93000,red,compact,clean,automatic,coupe,2010 Premium Nissan Altima 2.5 S,$7400,https://losangeles.craigslist.org/lgb/cto/d/2010-premium-nissan-altima-25/6678776004.html,Nissan,Altima
123,NaN,like new,4 cylinders,fwd,gas,35500,grey,compact,salvage,automatic,sedan,Nissan Altima 2016,$8900,https://losangeles.craigslist.org/sfv/cto/d/nissan-altima-2016/6668754210.html,Nissan,Altima
124,NaN,excellent,4 cylinders,NaN,gas,93,silver,NaN,lien,automatic,sedan,2014 Nissan Altima ~ RUNS AND LOOKS LIKE NEW !!,$7900,https://losangeles.craigslist.org/wst/cto/d/2014-nissan-altima-runs-and/6693052344.html,Nissan,Altima
125,NaN,excellent,4 cylinders,fwd,gas,43000,red,full-size,clean,automatic,sedan,Red Nissan Altima for sale!!,$15200,https://losangeles.craigslist.org/lgb/cto/d/red-nissan-altima-for-sale/6691582884.html,Nissan,Altima
126,1N4AL3AP2HC227456,like new,4 cylinders,rwd,gas,16700,blue,mid-size,salvage,automatic,sedan,"2017 NISSAN ALTIMA SR LOW 16,700 MILES, PADDLE SHIFTERS",$14950,https://losangeles.craigslist.org/sgv/cto/d/2017-nissan-altima-sr/6670254676.html,Nissan,Altima
127,NaN,good,4 cylinders,NaN,gas,160000,red,full-size,clean,automatic,sedan,2011 nissan Altima,$4300,https://losangeles.craigslist.org/lac/cto/d/2011-nissan-altima/6691029496.html,Nissan,Altima
128,1N4AL2APXCC141296,excellent,4 cylinders,fwd,gas,97121,black,full-size,clean,automatic,sedan,2012 Nissan ALTIMA 2.5S Excellent Custom Wheels,$8995,https://losangeles.craigslist.org/lac/cto/d/2012-nissan-altima-25s/6665053304.html,Nissan,Altima
129,NaN,excellent,4 cylinders,fwd,gas,97121,black,full-size,clean,automatic,sedan,2012 Nissan ALTIMA Custom wheels,$9995,https://losangeles.craigslist.org/lac/cto/d/2012-nissan-altima-custom/6666612375.html,Nissan,Altima
130,NaN,excellent,4 cylinders,NaN,gas,65472,NaN,NaN,salvage,automatic,NaN,2012 NISSAN ALTIMA COUPE civic tc g35 2013,$6500,https://losangeles.craigslist.org/lac/cto/d/2012-nissan-altima-coupe/6690752122.html,Nissan,Altima
131,NaN,good,4 cylinders,fwd,gas,75000,blue,mid-size,clean,automatic,sedan,2012 Nissan Altima 2.5 S,$6249,https://losangeles.craigslist.org/sgv/cto/d/2012-nissan-altima-25/6690378436.html,Nissan,Altima
132,NaN,good,4 cylinders,fwd,gas,152000,NaN,NaN,clean,automatic,NaN,2008 Nissan Altima 152k clean,$2800,https://losangeles.craigslist.org/lac/cto/d/2008-nissan-altima-152k-clean/6664233223.html,Nissan,Altima
133,NaN,excellent,4 cylinders,fwd,hybrid,89000,grey,full-size,salvage,automatic,sedan,Nissan altima 2011,$4800,https://losangeles.craigslist.org/lac/cto/d/nissan-altima-2011/6689656424.html,Nissan,Altima
134,NaN,good,4 cylinders,NaN,gas,106000,silver,NaN,clean,automatic,NaN,2012 Nissan altima,$5700,https://losangeles.craigslist.org/sfv/cto/d/2012-nissan-altima/6689401137.html,Nissan,Altima
135,NaN,excellent,4 cylinders,fwd,gas,11865,silver,NaN,missing,automatic,NaN,"2015 Nissan Altima 11k miles, 1 Owner, Moving Must Sell",$11500,https://losangeles.craigslist.org/lgb/cto/d/2015-nissan-altima-11k-miles/6689025699.html,Nissan,Altima
136,NaN,good,4 cylinders,fwd,gas,139000,white,mid-size,salvage,automatic,NaN,2012 Nissan altima,$6500,https://losangeles.craigslist.org/sfv/cto/d/2012-nissan-altima/6688587648.html,Nissan,Altima
137,NaN,good,4 cylinders,fwd,gas,56000,NaN,mid-size,salvage,automatic,sedan,2013 Nissan Altima S 56k millas,$6800,https://losangeles.craigslist.org/sfv/cto/d/2013-nissan-altima-56k-millas/6664964706.html,Nissan,Altima
138,1N4BL21E89N438180,good,6 cylinders,fwd,gas,184000,silver,mid-size,clean,automatic,sedan,2009 Nissan Altima 3.5SE,$4500,https://losangeles.craigslist.org/lac/cto/d/2009-nissan-altima-35se/6688450405.html,Nissan,Altima
139,NaN,like new,4 cylinders,NaN,gas,84,white,NaN,salvage,automatic,NaN,Nissan Altima 2015,$7500,https://losangeles.craigslist.org/lac/cto/d/nissan-altima-2015/6688272162.html,Nissan,Altima
140,NaN,good,4 cylinders,fwd,gas,70500,grey,mid-size,salvage,automatic,sedan,2010 NISSAN ALTIMA 2.5 SL,$6900,https://losangeles.craigslist.org/sgv/cto/d/2010-nissan-altima-25-sl/6687741706.html,Nissan,Altima
141,NaN,like new,4 cylinders,fwd,gas,14999,grey,NaN,clean,automatic,NaN,2016 Nissan Altima,$14999,https://losangeles.craigslist.org/lac/cto/d/2016-nissan-altima/6684035050.html,Nissan,Altima
142,NaN,good,6 cylinders,NaN,gas,153000,red,compact,clean,automatic,coupe,2011 Nissan Altima Coupe - PRICE REDUCED,$6700,https://losangeles.craigslist.org/ant/cto/d/2011-nissan-altima-coupe/6662655469.html,Nissan,Altima
143,NaN,good,4 cylinders,fwd,gas,111,NaN,NaN,clean,automatic,NaN,Nissan Altima,$5800,https://losangeles.craigslist.org/lac/cto/d/nissan-altima/6685821655.html,Nissan,Altima
144,NaN,good,4 cylinders,NaN,gas,74528,white,NaN,clean,automatic,sedan,Good,$6800,https://losangeles.craigslist.org/sfv/cto/d/good/6685574559.html,Nissan,Altima
145,NaN,good,NaN,NaN,gas,108000,black,NaN,clean,automatic,NaN,Nissan 2008 Altima coupe,$2800,https://losangeles.craigslist.org/lgb/cto/d/nissan-2008-altima-coupe/6685429639.html,Nissan,Altima
146,NaN,good,NaN,NaN,gas,85000,silver,NaN,clean,automatic,coupe,Nissan Altima Coupe for sale!!,$6000,https://losangeles.craigslist.org/wst/cto/d/nissan-altima-coupe-for-sale/6663901123.html,Nissan,Altima
147,NaN,good,4 cylinders,NaN,gas,80000,black,NaN,clean,automatic,coupe,Nissan Altima Coupe 2012 - Black 80K Miles - Runs Amazing *Cash Only*,$8000,https://losangeles.craigslist.org/sfv/cto/d/nissan-altima-coupe-2012/6685334820.html,Nissan,Altima
148,NaN,like new,4 cylinders,fwd,gas,48400,black,mid-size,clean,automatic,sedan,Nissan Altima 2015 2.5 S,$9900,https://losangeles.craigslist.org/lac/cto/d/nissan-altima/6658609275.html,Nissan,Altima
149,NaN,like new,4 cylinders,NaN,gas,65000,grey,NaN,clean,automatic,NaN,Nissan Altima coupe 010,$7999,https://losangeles.craigslist.org/lac/cto/d/nissan-altima-coupe-010/6666027001.html,Nissan,Altima
150,NaN,excellent,4 cylinders,NaN,gas,50000,white,full-size,clean,automatic,sedan,2016 Nissan Altima 2.5 Clean Title,$11800,https://losangeles.craigslist.org/lac/cto/d/2016-nissan-altima-25-clean/6684447019.html,Nissan,Altima
151,NaN,good,4 cylinders,fwd,gas,144000,black,compact,salvage,manual,coupe,2009 Nissan Altima Coupe,$3200,https://losangeles.craigslist.org/lac/cto/d/2009-nissan-altima-coupe/6684327820.html,Nissan,Altima
152,NaN,excellent,4 cylinders,fwd,gas,89923,silver,full-size,clean,automatic,sedan,7997 2012 Nissan Altima 2.5S,$7995,https://losangeles.craigslist.org/lgb/cto/d/nissan-altima-25s/6683679875.html,Nissan,Altima

In [7]:
# Out put as CSV file
accord_df.to_csv(csv_file_path)

In [ ]:
text2list = text2.split() #Splits words in tag string to items in list
text2list =[x.upper() for x in text2list] #Converts Items in list to uppercase for comparison sake

#Below is a list of all brands of cars
BrandList = ["ACURA","ARASH","ALFA","ROMEO","ALFA-ROMEO","ALFA ROMEO","ARIEL","ASCARI","ASTON","MARTIN","ASTON MARTIN","AUDI","BENTLEY","BOWLER","BMW","BRIGGS","BRISTOL","BROOKE","BUGATTI","BUICK","CADILLAC","CAPARO","CATERHAM","CHERY","CHEVROLET","CHEVRON","CHRYSLER","CITROEN","CORVETTE","DAIHATSU","DATSUN","DODGE","DONKERVOORT","FERRARI","FIAT","FISKER","FORD","FPV","GINETTA","GMC","HENNESSEY","HOLDEN","HONDA","HYUNDAI","INFINITI","ISUZU","JAGUAR","JEEP","JOSS","KAMAZ","KIA","KOENIGSEGG","KTM (X-BOW)","LAMBORGHINI","LANCIA","LAND ROVER","LEXUS","LISTER","LINCOLN","LOTUS","MAHINDRA","MARUTISUZUKI","MASERATI","MASTRETTA","MAZDA","MCLAREN","MERCEDES","BENZ","MERCEDES-BENZ","MG MOTOR","MINI","MITSUBISHI","MORGAN","NISSAN","NOBLE","OPEL","PAGANI","PERODUA","PEUGEOT","PORSCHE","PROTON","RADICAL","RAM","RENAULT","ROEWE","ROLLS","ROYCE","ROLLS-ROYCE","RUF","SALEEN","SAAB","SCION","SEAT","SKODA","SMART","SRT","SSANGYONG","SUBARU","SUPERFORMANCE","SUZUKI","TATA","TESLA","TOYOTA","TVR","ULTIMA","VAUXHALL","VENTURI","VOLKSWAGEN","VOLVO","WESTFIELD","WIESMANN","ZENVO","ALPINE","AMERICAN","ASIA","AUSTIN","HEALEY","AUSTIN-HEALEY","DAEWOO","DE TOMASO","DEVON","GUMPERT","HUMMER","INVICTA","MARCOS","MAYBACH","MORRIS","OLDSMOBILE","PLYMOUTH","PONTIAC","SATURN","SPYKER"]

yearlist = list(range(1900, 2020)) #All possible years
stryearlist = [str(item) for item in yearlist] #convert  int years in yearlist to string

mergedlist = BrandList + stryearlist #Merge list of brands and years. To be used to get model of cars

Makelist = list(set(BrandList) & set(text2list)) # Sets a new list of car make
Make = concatenate_list_data(Makelist)
print(Make)

modelist = [x for x in text2list if x not in mergedlist] # Sets a new list of car model
Model = concatenate_list_data(modelist)
print(Model)

yearlist = list(set(stryearlist) & set(text2list)) # Sets a new list of car year
Year = concatenate_list_data(yearlist)
print(Year)

In [17]:
def concatenate_list_data(list): #Concatenates items in list to one string
    result= ''
    for element in list:
        result += str(element + ' ')
    return result
titles = car_df["Title"]
Years = []
for title in titles:
    titlelist = title.split() #Splits words in tag string to items in list
    titlelist =[x.upper() for x in titlelist] #Converts Items in list to uppercase for comparison sake

    #Below is a list of all brands of cars
    BrandList = ["ACURA","ARASH","ALFA","ROMEO","ALFA-ROMEO","ALFA ROMEO","ARIEL","ASCARI","ASTON","MARTIN","ASTON MARTIN","AUDI","BENTLEY","BOWLER","BMW","BRIGGS","BRISTOL","BROOKE","BUGATTI","BUICK","CADILLAC","CAPARO","CATERHAM","CHERY","CHEVROLET","CHEVRON","CHRYSLER","CITROEN","CORVETTE","DAIHATSU","DATSUN","DODGE","DONKERVOORT","FERRARI","FIAT","FISKER","FORD","FPV","GINETTA","GMC","HENNESSEY","HOLDEN","HONDA","HYUNDAI","INFINITI","ISUZU","JAGUAR","JEEP","JOSS","KAMAZ","KIA","KOENIGSEGG","KTM (X-BOW)","LAMBORGHINI","LANCIA","LAND ROVER","LEXUS","LISTER","LINCOLN","LOTUS","MAHINDRA","MARUTISUZUKI","MASERATI","MASTRETTA","MAZDA","MCLAREN","MERCEDES","BENZ","MERCEDES-BENZ","MG MOTOR","MINI","MITSUBISHI","MORGAN","NISSAN","NOBLE","OPEL","PAGANI","PERODUA","PEUGEOT","PORSCHE","PROTON","RADICAL","RAM","RENAULT","ROEWE","ROLLS","ROYCE","ROLLS-ROYCE","RUF","SALEEN","SAAB","SCION","SEAT","SKODA","SMART","SRT","SSANGYONG","SUBARU","SUPERFORMANCE","SUZUKI","TATA","TESLA","TOYOTA","TVR","ULTIMA","VAUXHALL","VENTURI","VOLKSWAGEN","VOLVO","WESTFIELD","WIESMANN","ZENVO","ALPINE","AMERICAN","ASIA","AUSTIN","HEALEY","AUSTIN-HEALEY","DAEWOO","DE TOMASO","DEVON","GUMPERT","HUMMER","INVICTA","MARCOS","MAYBACH","MORRIS","OLDSMOBILE","PLYMOUTH","PONTIAC","SATURN","SPYKER"]

    yearlist = list(range(1900, 2020)) #All possible years
    stryearlist = [str(item) for item in yearlist] #convert  int years in yearlist to string

    mergedlist = BrandList + stryearlist #Merge list of brands and years. To be used to get model of cars

    Makelist = list(set(BrandList) & set(titlelist)) # Sets a new list of car make
    Make = concatenate_list_data(Makelist)
    print(Make)

    modelist = [x for x in titlelist if x not in mergedlist] # Sets a new list of car model
    Model = concatenate_list_data(modelist)
    print(Model)

    yearlist = list(set(stryearlist) & set(titlelist)) # Sets a new list of car year
    Year = concatenate_list_data(yearlist)
    Years.append(Year)
    
Years

NISSAN
ALTIMA 2.5S
NISSAN
ALTIMA 124,000 MILES
NISSAN
ALTIMA 4C SEDAN
NISSAN
ALTIMA S SEDAN WHITE 99,000MILES
NISSAN
ALTIMA LOW MILEAGE CLEAN
NISSAN
ALTIMA LOW MILEAGE CLEAN
NISSAN
ALTIMA LOW MILEAGE CLEAN
NISSAN
ALTIMA CUSTOM WHEELS EXCELLENT
NISSAN
ALTIMA S WITH BACKUP CARMERA
NISSAN
ALTIMA VERY CLEAN I WOULD CONSIDER TAKING PAYMENTS
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA 2.5
NISSAN
ALTIMA SL
NISSAN
ALTIMA
NISSAN
ALTIMA 2.5S - CLEAN TITLE - LOW MILES
NISSAN
ALTIMA COUPE
NISSAN
ALTIMA 2.5 S NEW BODY STYLE
NISSAN
ALTIMA
NISSAN
ALTIMA (BOSE AUDIO)
NISSAN
ALTIMA 80K CLEAN TITLE
NISSAN
ALTIMA 2.5L
NISSAN
ALTIMA 3.5 SE FULLY LOADED.
NISSAN
ALTIMA S LOW MILEAGE GREAT DEAL
NISSAN
ALTIMA 2.5 SL BLACK LEATHER LOW MILES
NISSAN
ALTIMA LOW MILEAGE CLEAN
NISSAN
ALTIMA 2.5S
NISSAN
ALTIMA SV/CLEAN TITLE/36K MILES
NISSAN
ALTIMA S WITH BACKUP CARMERA
NISSAN
ALTIMA S SEDAN WHITE 99,000MILES
NISSAN
ALTIMA 2.5 S 2DOORS SEDAN
NISSAN
ALTIMA
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA SL ... ONLY 48K MILES ... EXTRA CLEAN ... MUST SEE
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA LOW MILEAGE 59,400 MILES
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA 2.5
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA 2.5S SEDAN
NISSAN
ALTIMA SR, 4DR BLACK
NISSAN
ALTIMA
NISSAN
ALTIMA S WITH BACKUP CARMERA
NISSAN
ALTIMA S 2.5 (GAS SAVER)
NISSAN
ALTIMA
NISSAN
ALTIMA SL

ALTIMA 3.5 SE
NISSAN
ALTIMA S (LOW MILES!)
NISSAN
ALTIMA HYBRID PERFECT RUNNER SMOGGED 3/19TAGS CLEAN TITLE
NISSAN
ALTIMA 2.5
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA HYBRID.. I WOULD CONSIDER TAKING PAYMENTS FOR THE CAR
NISSAN
ALTIMA
NISSAN
ALTIMA CLEAN CARFAX CLEAN TITLE IN HAND GREAT ECONOMICAL VEHICLE
NISSAN
ALTIMA S WITH BACKUP CARMERA
NISSAN
ALTIMA SL
NISSAN
ALTIMA WITH WARRANTY
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA S SEDAN 4D
NISSAN
ALTIMA S SEDAN
NISSAN
ALTIMA HYBRID.. I WOULD CONSIDER TAKING PAYMENTS FOR THE CAR
NISSAN
ALTIMA
NISSAN
ALTIMA 2.5S EXCELLENT CONDITION

ALTIMA 2.5
NISSAN
----2017 ALTIMA 2.5---LIKE NEW--WHITE---MUST SEE---

SPORTS CAR!
NISSAN
ALTIMA S WITH BACKUP CARMERA
NISSAN
MAXIMA
NISSAN
ALTIMA HYBRID
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA S WITH BACKUP CARMERA

ALTIMA 2.5S
NISSAN
ALTIMA S
NISSAN
ALTIMA HYBRID BASE
NISSAN
ALTIMA VERY CLEAN I WOULD CONSIDER TAKING PAYMENTS
NISSAN
ALTIMA 3.5 SE COUPE


NISSAN
ALTIMA S CON 133K MILLAS EN OFERTA
NISSAN
ALTIMA S CON 133K MILLAS EN OFERTA
NISSAN
ALTIMA $4000
NISSAN
ALTIMA
NISSAN
STUNNING BLACK ALTIMA, CLEAN NOT SALVAGED!
NISSAN
ALTIMA 3.5 V6 COUPE SE
NISSAN
ALTIMA 3.5 V6 COUPE SE
NISSAN
ALTIMA HYBRID COLD A/C PERFECT RUNNER 4/19TAGS CLEAN TITLE
NISSAN
ALTIMA
NISSAN
ALTIMA SV/CLEAN TITLE/36K MILES
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA 2.5S
NISSAN
ALTIMA 2.5 SL LEATHER SUNROOF HEATED SEATS FULLY LOADED

2014NISSAN ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA SALVAGED
NISSAN
LIKE NEW ALTIMA COUPE
NISSAN
ALTIMA FOR SALE!
NISSAN
ALTIMA 2.5S, 1 OWNER, FULL SERVICE RECORDS, 60K MILES
NISSAN
ALTIMA
NISSAN
*GREAT DEAL* ALTIMA SV
NISSAN
09 ALTIMA
NISSAN
ALTIMA 2.5
NISSAN
ALTIMA
NISSAN
ALTIMA SR, BLACK/BLACK INT 4 CILINDERS
NISSAN
ALTIMA S,NO ACCIDENTS,WELL MAINTAINED!!
NISSAN
ALTIMA HYBRID
NISSAN
ALTIMA SL 16K MILAGE LEATHER
NISSAN
ALTIMA * 4 CLY * AUTO * * SALE, SALE, SALE * *
NISSAN
ALTIMA
NISSAN
*********************** ALTIMA
NISSAN
ALTIMA FOR SALE
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA SV
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
PREMIUM ALTIMA 2.5 S
NISSAN
ALTIMA
NISSAN
ALTIMA ~ RUNS AND LOOKS LIKE NEW !!
NISSAN
RED ALTIMA FOR SALE!!
NISSAN
ALTIMA SR LOW 16,700 MILES, PADDLE SHIFTERS
NISSAN
ALTIMA
NISSAN
ALTIMA 2.5S EXCELLENT CUSTOM WHEELS
NISSAN
ALTIMA CUSTOM WHEELS
NISSAN
ALTIMA COUPE CIVIC TC G35
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA 152K CLEAN
NISSAN
ALTIMA
NISSAN
ALTIMA
NISSAN
ALTIMA 11K MILES, 1 OWNER, MOVING MUST SELL
NISSAN
ALTIMA
NISSAN
ALTIMA S 56K MILLAS
NISSAN
ALTIMA 3.5SE
NISSAN
ALTIMA
NISSAN
ALTIMA 2.5 SL
NISSAN
ALTIMA
NISSAN
ALTIMA COUPE - PRICE REDUCED
NISSAN
ALTIMA

GOOD
NISSAN
ALTIMA COUPE
NISSAN
ALTIMA COUPE FOR SALE!!
NISSAN
ALTIMA COUPE - BLACK 80K MILES - RUNS AMAZING *CASH ONLY*
NISSAN
ALTIMA 2.5 S
NISSAN
ALTIMA COUPE 010
NISSAN
ALTIMA 2.5 CLEAN TITLE
NISSAN
ALTIMA COUPE
NISSAN
7997 ALTIMA 2.5S

['2008 ',
 '2009 ',
 '2016 ',
 '2015 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2012 ',
 '2014 ',
 '2012 ',
 '2015 ',
 '2016 2017 ',
 '2013 ',
 '',
 '2012 ',
 '2012 ',
 '',
 '2008 ',
 '2009 ',
 '2012 ',
 '2008 ',
 '2009 ',
 '2015 ',
 '2015 ',
 '2014 ',
 '2012 ',
 '2017 ',
 '2014 ',
 '2015 ',
 '2008 ',
 '2011 ',
 '2010 ',
 '2015 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2011 ',
 '2016 ',
 '2008 ',
 '2008 ',
 '2012 ',
 '2013 2016 2014 2015 ',
 '2011 ',
 '2014 ',
 '2014 ',
 '2011 ',
 '2010 ',
 '2008 ',
 '2012 ',
 '2009 ',
 '2009 ',
 '2013 ',
 '2008 ',
 '2009 ',
 '2008 ',
 '2011 ',
 '2014 ',
 '2013 ',
 '2008 ',
 '2014 ',
 '2011 ',
 '2011 ',
 '2009 ',
 '',
 '2010 ',
 '2008 ',
 '',
 '',
 '2014 ',
 '2011 ',
 '2008 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2014 ',
 '2010 ',
 '2014 ',
 '2009 ',
 '2012 ',
 '2008 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2010 ',
 '2009 ',
 '2017 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2012 ',
 '2017 ',
 '2012 ',
 '2010 ',
 '2010 ',
 '2012 ',
 '2009 ',
 '',
 '2012 ',
 '2014 ',
 '',
 '2008 ',
 '2011 ',
 '2010 ',
 '2013 ',
 '',
 '2015 ',
 '2014 ',
 '2016 ',
 '2015 ',
 '2008 ',
 '2017 ',
 '2012 ',
 '2010 ',
 '2012 ',
 '2009 ',
 '2012 ',
 '2012 ',
 '2011 ',
 '2015 ',
 '2009 ',
 '2012 ',
 '2010 ',
 '2016 ',
 '2014 ',
 '',
 '2017 ',
 '2011 ',
 '2012 ',
 '2012 ',
 '2013 2012 ',
 '2012 ',
 '2008 ',
 '2011 ',
 '2012 ',
 '2015 ',
 '2012 ',
 '2013 ',
 '2009 ',
 '2015 ',
 '2010 ',
 '2016 ',
 '2011 ',
 '',
 '',
 '2008 ',
 '',
 '2012 ',
 '2015 ',
 '',
 '2016 ',
 '2009 ',
 '2012 ']

In [22]:
yearlist

['2012']

In [18]:
len(Years)

153

In [21]:
list(range(1900, 2020))

[1900,
 1901,
 1902,
 1903,
 1904,
 1905,
 1906,
 1907,
 1908,
 1909,
 1910,
 1911,
 1912,
 1913,
 1914,
 1915,
 1916,
 1917,
 1918,
 1919,
 1920,
 1921,
 1922,
 1923,
 1924,
 1925,
 1926,
 1927,
 1928,
 1929,
 1930,
 1931,
 1932,
 1933,
 1934,
 1935,
 1936,
 1937,
 1938,
 1939,
 1940,
 1941,
 1942,
 1943,
 1944,
 1945,
 1946,
 1947,
 1948,
 1949,
 1950,
 1951,
 1952,
 1953,
 1954,
 1955,
 1956,
 1957,
 1958,
 1959,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 1968,
 1969,
 1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019]

In [26]:
yearlist = [str(num) for num in list(range(1900, 2020))]
yearlist

['1900',
 '1901',
 '1902',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1908',
 '1909',
 '1910',
 '1911',
 '1912',
 '1913',
 '1914',
 '1915',
 '1916',
 '1917',
 '1918',
 '1919',
 '1920',
 '1921',
 '1922',
 '1923',
 '1924',
 '1925',
 '1926',
 '1927',
 '1928',
 '1929',
 '1930',
 '1931',
 '1932',
 '1933',
 '1934',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1948',
 '1949',
 '1950',
 '1951',
 '1952',
 '1953',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019']